version: "1.0"
apps:
  - id: 7zip
    manager: scoop
  - id: git
    manager: scoop
  - id: wget
    manager: choco
  - id: "tpope/vim-fugitive"
    manager: "vim"
envVars:
  - variable: "WINHOME_TEST"
    value: "true"
    action: "set"
dotfiles:
  - src: "README.md"
    target: "test-dotfile.md"
registryTweaks:
  - path: 'HKCU\Software\WinHomeTest'
    name: "TestValue"
    value: 123
    type: "dword"
systemSettings:
  show_file_extensions: true
git:
  userName: "WinHome Test"
  userEmail: "test@winhome.local"
  settings:
    init.defaultBranch: main
extensions:
  vim:
    settings:
      number: true