version: "1.0"
apps:
  - id: 7zip.7zip
    manager: winget
envVars:
  - variable: "WINHOME_TEST_GHA"
    value: "true"
    action: "set"
dotfiles:
  - src: "README.md"
    target: "~/test-dotfile-gha.md"
registryTweaks:
  - path: 'HKCU\Software\WinHomeGHA'
    name: "GHATest"
    value: 456
    type: "dword"
systemSettings:
  show_file_extensions: true
git:
  userName: "WinHome GHA"
  userEmail: "gha@winhome.local"
